### ISSUE TITLE
`JsonSyntaxException` when using `GetUserProfile` 

### ISSUE THREAD

**Issue by TapiocaFox** [RetroAchievements/api-kotlin#10]
Hey Mr. Wizard. I've tried to update Daijishou with your API recently. But I encountered an Issue below when I use `GetUserProfile`. I've tried other options like `GetUserSummary` and it works correctly. Could you enlighten me, or it could be a bug?

```         
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected an int but was BOOLEAN at line 1 column 307 path $.UserWallActive
```

Thank you very much.

**Comment by TapiocaFox** [comment]
And I found out `UserWallActive` is inconsistent between different endpoints. Take a look at responses from API docs:

### User Profile (Boolean)
```
  "ID": 16446,
  "UserWallActive": true,
  "Motto": "Join me on Twitch! GameSquadSquad for live RA"
```

### User Summary (Integer)
```
  "ID": 224958,
  "UserWallActive": 1,
  "Motto": "",
```

**Comment by official-wizard** [comment]
Yes, unfortunately this inconsistency will have to be remedied on our end as to not break compatibility with other programs depending on that value being an Integer.

**Comment by TapiocaFox** [comment]
Thanks!
